[database_connection]
database = "bnuybase"
socket_path = "/run/mysqld/mysqld.sock"
user = "xenia"

[http_server]
listen_addr = "127.0.0.1:8080"

[sftp_server]
listen_addr = "127.0.0.1:2222"
# generate these with ssh-keygen -t ed25519 -f keys/sftp_ed25519
private_key = "./keys/sftp_ed25519"
public_key = "./keys/sftp_ed25519.pub"


# [storage_nodes.bnuy-1]
# addr = "127.0.0.1:1312"

# [storage_nodes.bnuy-2]
# addr = "127.0.0.2:1312"

[storage_nodes.catboy-cafe]
addr = "10.100.100.254:1312"

[storage_nodes.xn--skrbrda-6wad]
addr = "10.100.100.1:1312"
