[connection_options]
database = "bnuybase"
socket_path = "/run/mysqld/mysqld.sock"
user = "xenia"

[storage_nodes.bnuy-1]
addr = "127.0.0.1:1312"

[storage_nodes.bnuy-2]
addr = "127.0.0.2:1312"

[storage_nodes.catboy-cafe]
addr = "192.168.2.254:1312"

[storage_nodes.xn--skrbrda-6wad]
addr = "192.168.2.1:1312"
